update message

diff --git a/script/axe-docs b/script/axe-docs
--- a/script/axe-docs
+++ b/script/axe-docs
@@ -1,13 +1,19 @@
 #!/bin/bash
 
 # This workflow runs axe checks on modified doc/content/components/* or doc/content/components/* pages because those include code examples.
-# Developers frequently copy and paste examples from documentation so it's important to ensure the examples are accessible.
+# Developers frequently copy and paste examples directly so it's important to ensure the examples are accessible.
 # Learn about @axe-core/cli: https://github.com/dequelabs/axe-core-npm/tree/develop/packages/cli
 
-array=($MODIFIED_COMPONENT_OR_UTILITIES_PATHS)
-printf "%s\n" "${array[@]}" > temp.txt
+if [ -z "$STRING_OF_PATHS_WE_CARE_ABOUT" ]; then
+  echo "The script cannot run because STRING_OF_PATHS_WE_CARE_ABOUT is not correctly set for some reason"
+  echo "Exiting..."
+  exit 1
+else
+  array=($STRING_OF_PATHS_WE_CARE_ABOUT)
+  printf "%s\n" "${array[@]}" > temp.txt
+fi
 
-# Store the paths of pages we care about
+echo "Parsing paths from the filenames..."
 nav_paths=()
 while IFS= read -r file
 do
@@ -19,11 +25,6 @@ do
 done < temp.txt
 rm temp.txt
 
-# Return early if no relevant files were modified
-echo "Verify whether ${nav_paths[@]} is part of starting point violation"
-echo "*"
-echo "*"
-
 # https://stackoverflow.com/a/8574392
 containsElement () {
   local e match="$1"
@@ -34,7 +35,7 @@ containsElement () {
 
 # Starting point violations
 # DO NOT ADD TO THIS LIST!
-skipped=(
+needs_to_be_fixed=(
   /components/autocomplete
   /components/avatars
   /components/box
@@ -50,7 +51,9 @@ skipped=(
   /utilities/layout 
 )
 
-# Generate doc urls for testing
+echo "Removing paths that are part of the starting point violations list:"
+printf '%s\n' "${needs_to_be_fixed[@]}"
+
 doc_urls=()
 skipped=()
 for i in "${nav_paths[@]}"; 
@@ -66,24 +69,28 @@ do
 done
 
 if (( ${#skipped[@]} )); then
-  echo "############################################################"
+  echo "==========================================================================================="
   echo "WARNING"
-  echo "The following paths are excluded from axe checks because they are part of starting point violations:"
-  printf '%s\n' "${needs_to_be_fixed[@]}"
   echo ""
+  echo "Oh no! We had to skip accessibility checks on:"
   echo ""
-  echo "While you're working in:"
   printf '%s\n' "${skipped[@]}"
-  echo "will you consider fixing the accessibility issues so we can remove it from the list? ❤️"
-  echo "############################################################"
+  echo ""
+  echo "because they are part of the starting point violations list."
+  echo ""
+  echo "Help us get one closer to getting rid of this list!"
+  echo "Consider addressing the accessibility issues on the examples of these pages as part of your PR ❤️"
+  echo "==========================================================================================="
 fi
 
 # Run axe checks only if there are pages to run it on
 if [ ${#doc_urls[@]} -eq 0 ]; then
   exit
 else
+  echo "Installing axe..."
   npm install -g @axe-core/cli
   # https://github.com/dequelabs/axe-core-npm/tree/develop/packages/cli
   # We exclude rules that depend on full page context.
+  echo "Running axe..."
   axe ${doc_urls[@]} --include "iframe" --disable html-has-lang,frame-title,page-has-heading-one,region,color-contrast,landmark-unique,landmark-one-main --exit --show-errors
 fi
