ci: don't check links on Travis
...unless "[check-links]" is in the commit message

diff --git a/script/deploy-docs b/script/deploy-docs
--- a/script/deploy-docs
+++ b/script/deploy-docs
@@ -27,7 +27,7 @@ else
     npx commit-status pending docs "deploying v$version docs..."
 
     echo "deploying..."
-    now $now_args | tee now-url.txt
+    now "$now_args" | tee now-url.txt
     url=$(cat now-url.txt)
     npx commit-status success docs "v$version docs: $url" "$url"
 
@@ -43,22 +43,23 @@ else
         alias="primer-css-${branch//\./-}.now.sh"
     fi
     echo "aliasing to '$alias'..."
-    now $now_args alias $url $alias
+    now "$now_args" alias "$url" "$alias"
     npx commit-status success docs "v$version docs: $alias" "https://$alias"
 
-    exit 0
-    echo
-    echo "Running script/check-links in $(pwd)..."
-    echo
-    script/check-links -v -m=5 "https://$alias/css" || {
+    if [[ "$TRAVIS_COMMIT_MESSAGE" =~ \[check-links\] ]]; then
         echo
-        echo "⚠️  Link check failed! ⚠️"
+        echo "Running script/check-links in $(pwd)..."
         echo
-        echo "Check the report above for more info, and/or run:"
-        echo
-        echo "    script/check-links http://localhost:3000 -v"
-        echo
-        echo "locally for more info."
-        exit 1
-    }
+        script/check-links -v -m=5 "https://$alias/css" || {
+            echo
+            echo "⚠️  Link check failed! ⚠️"
+            echo
+            echo "Check the report above for more info, and/or run:"
+            echo
+            echo "    script/check-links http://localhost:3000 -v"
+            echo
+            echo "locally for more info."
+            exit 1
+        }
+    fi
 fi
