run script/check-links after deploying docs

diff --git a/script/deploy-docs b/script/deploy-docs
--- a/script/deploy-docs
+++ b/script/deploy-docs
@@ -43,9 +43,14 @@ else
     now $now_args alias $url $alias
     npx commit-status success docs "v$version docs: $alias" "https://$alias"
 
-    npx blc -ogr "https://$alias/css" || {
-        echo "*** There are some broken links! ***"
-        echo "Check the report above for more info, and/or"
-        echo "run script/check-local-links locally for fast checks."
+    script/check-links "https://$alias/css" || {
+        echo
+        echo "⚠️  Link check failed! ⚠️"
+        echo
+        echo "Check the report above for more info, and/or run:"
+        echo
+        echo "    script/check-links -rv http://localhost:3000"
+        echo
+        echo "locally for more info."
     }
 fi
